language: node_js
node_js:
- 7
script:
- npm test
- npm run build
#Deploy build to Github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
