language: node_js
node_js:
- 7
script:
- npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- npm run build
#Deploy build to Github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
